# you have to create .env file next to this file with credentials for it to work
# also put microservices databases credentials here as well as in init-db/create_databases.sql
services:
  db:
    image: postgres:latest
    environment:
      # POSTGRES_DB: main_db   # The default database
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/  # Mount the custom script
      # - ./db_data:/var/lib/postgresql/data
