# you have to create .env file next to this file with credentials for it to work
# also put microservices databases credentials here as well as in init-db/create_databases.sql
services:
  db-psql:
    image: postgres:latest
    environment:
      # POSTGRES_DB: main_db   # The default database
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db_postgres/init-db:/docker-entrypoint-initdb.d/  # Mount the custom script
      - ./db_postgres/db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}    # Admin email for pgAdmin login
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} # Admin password for pgAdmin login
    ports:
      - "8080:80"  # Expose pgAdmin on port 8080
    depends_on:
      - db-psql    # Ensure that PostgreSQL starts before pgAdmin
    volumes:
      - ./pgadmin/pgadmin_data:/var/lib/pgadmin   # Optional: Persistent pgAdmin data
