# this is the version of the docker-compose file that is merged with the docker-compose.yml file if no other file is specified
# to run:
#  docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build

# services:
# mongo:
#   ports:
#     - "27017:27017"
#   stdin_open: true # not sure if this is needed
#   tty: true # not sure if this is needed

# mongo_express:
#   ports:
#     - "8081:8081"

# backup_service:
#   build:
#     target: development # in Dockerfile
#   # ports:
#   #   - "3000:3000" # Expose the NestJS application port
#   volumes:
#     - ./backup_service:/app
#     - /app/node_modules
#   stdin_open: true
#   tty: true

# auth_and_permissions:
#   build:
#     target: development # in Dockerfile
#   # ports:
#   #   - "3000:3000" # Expose the NestJS application port
#   volumes:
#     - ./auth_and_permissions:/app
#     - /app/node_modules
#   stdin_open: true
#   tty: true

# recruitment_survey_phase:
#   build:
#     target: development # in Dockerfile
#   # ports:
#   #   - "3000:3000" # Expose the NestJS application port
#   volumes:
#     - ./recruitment_survey_phase:/app
#     - /app/node_modules
#   stdin_open: true
#   tty: true

# recruitment_interview_phase:
#   build:
#     target: development # in Dockerfile
#   # ports:
#   #   - "3000:3000" # Expose the NestJS application port
#   volumes:
#     - ./recruitment_interview_phase:/app
#     - /app/node_modules
#   stdin_open: true
#   tty: true

# newsletter:
#   build:
#     target: development # in Dockerfile
#   # ports:
#   #   - "3000:3000" # Expose the NestJS application port
#   volumes:
#     - ./newsletter:/app
#     - /app/node_modules
#   stdin_open: true
#   tty: true

# availability:
#   build:
#     target: development # in Dockerfile
#   # ports:
#   #   - "3000:3000" # Expose the NestJS application port
#   volumes:
#     - ./availability:/app
#     - /app/node_modules
#   stdin_open: true
#   tty: true

# frontend:
#   build:
#     target: development # in Dockerfile
#   # ports:
#   #   - "8080:8080"
#   volumes:
#     - ./frontend:/app
#     - /app/node_modules
#   stdin_open: true
#   tty: true
