# you have to create .env file next to this file with credentials for it to work
# also put microservices databases credentials here as well as in init-db/create_databases.sql
services:
  db-psql:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # UNCOMMENT THIS TO PERSIST DATA
    # volumes:
      # - ./db_postgres/db_data:/var/lib/postgresql/data
    configs:
      - source: db-psql-create_databases.sql
        target: /docker-entrypoint-initdb.d/create_databases.sql

  pgadmin:
    build:
      context: .
      dockerfile: ./pgadmin/dockerfile_for_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL_PART_BEFORE_AT}@${PGADMIN_DEFAULT_EMAIL_PART_AFTER_AT}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
       - "5050:80"
    # process to find this was pain
    entrypoint: >
      /bin/sh -c "
      mkdir -p /var/lib/pgadmin/storage/${PGADMIN_DEFAULT_EMAIL_PART_BEFORE_AT}_${PGADMIN_DEFAULT_EMAIL_PART_AFTER_AT}/;
      cp /tmp/mountpoint.pgpass /var/lib/pgadmin/storage/${PGADMIN_DEFAULT_EMAIL_PART_BEFORE_AT}_${PGADMIN_DEFAULT_EMAIL_PART_AFTER_AT}/.pgpass;
      chown pgadmin:root /var/lib/pgadmin/storage/${PGADMIN_DEFAULT_EMAIL_PART_BEFORE_AT}_${PGADMIN_DEFAULT_EMAIL_PART_AFTER_AT}/.pgpass;
      chmod 600 /var/lib/pgadmin/storage/${PGADMIN_DEFAULT_EMAIL_PART_BEFORE_AT}_${PGADMIN_DEFAULT_EMAIL_PART_AFTER_AT}/.pgpass;
      /entrypoint.sh
      "
    configs:
      - source: pgadmin-servers.json
        target: /pgadmin4/servers.json
      - source: pgadmin-pgpass
        target: /tmp/mountpoint.pgpass

configs:
  db-psql-create_databases.sql:
    content: |
      /*
        login to superuser:
        docker exec -it db_postgres-db-1 psql -U <user_name_from_docker_compose_env_file>

        login to user:
        docker exec -it db_postgres-db-1 psql -U <user_name> -d <db_name>

        WARNING: if you change env variables later on, you can lose all data in the database (can't login)

        used this to make file not tracked anymore by git:
        git update-index --skip-worktree db_postgres/init-db/create_databases.sql
      */

      /* using '-' in env variables here is discouraged as it requires escaping */

      -- first microservice
      CREATE DATABASE "${AUTH_SERVICE_DB_NAME}";
      CREATE USER "${AUTH_SERVICE_DB_USER}" WITH PASSWORD '${AUTH_SERVICE_DB_PASSWORD}';
      GRANT ALL PRIVILEGES ON DATABASE "${AUTH_SERVICE_DB_NAME}" TO "${AUTH_SERVICE_DB_USER}";
  pgadmin-pgpass:
    content: db-psql:5432:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}
  pgadmin-servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "PostgreSQL",
            "Group": "Servers",
            "Host": "db-psql",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "${POSTGRES_USER}",
            "ConnectionParameters": {
              "sslmode": "prefer",
              "connect_timeout": "10",
              "passfile": "/.pgpass"
            }
          }
        }
      }
