# FROM dpage/pgadmin4
# USER pgadmin
# RUN mkdir -p  /var/lib/pgadmin/storage/pgadmin_pgadmin.com
# COPY ./pgadmin/pgpass /var/lib/pgadmin/storage/pgadmin_pgadmin.com/
# USER root
# # RUN chown pgadmin:pgadmin /var/lib/pgadmin/storage/pgadmin_pgadmin.com/pgpass
# RUN chmod 0600 /var/lib/pgadmin/storage/pgadmin_pgadmin.com/pgpass
# USER pgadmin
# ENTRYPOINT ["/entrypoint.sh"]

FROM dpage/pgadmin4:latest as base

RUN touch /tmp/mountpoint.pgpass; \
    chmod 600 /tmp/mountpoint.pgpass;

USER root
RUN touch /pgadmin4/servers.json; \
    chmod 644 /pgadmin4/servers.json;
